url: https://github.com/SkyroverTech/skyrovertech.github.com
baseurl: 

# Site settings
title: SkyroverTech System Team
email: ccharlieli@live.com
description: "Meet the SkyroverTech System Team! We are a group of geeks, nerds and dreamers, we build things that fly in the sky."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Charlie Li
  pic: 1
  position: Team Leader
  social:
    - title: weibo
      url: http://weibo.com/lichao449217425
    - title: linkedin
      url: http://www.linkedin.com/profile/view?id=299803353
    - title: github
      url: https://github.com/CCharlieLi
    - title: google
      url: #

- name: philip knight
  pic: 2
  position: Lead Marketer
  social:
    - title: weibo
      url: http://www.weibo.com/1831279011/profile?rightmod=1&wvr=6&mod=personinfo
    - title: facebook
      url: www.facebook.com/profile.php?id=100010051353421
    - title: linkedin
      url: http://www.linkedin.com/profile/view?id=AAIAABjycjABidEn7i2T0yGclahtyjMlfqGGXaA&trk=nav_responsive_tab_profile_pic

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: weibo
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/skyrovertech

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty